flowchart TD
%% generated in 0.06s
    services__orchestrator["services.orchestrator<br/>432 funcs"]
    services__projector["services.projector<br/>67 funcs"]
    services__web["services.web<br/>816 funcs"]
    services__orchestrator -->|3| services__web
    services__orchestrator -->|1| services__projector
