flowchart TD
%% generated in 0.03s
    services__orchestrator["services.orchestrator<br/>429 funcs"]
    services__projector["services.projector<br/>67 funcs"]
    services__web["services.web<br/>639 funcs"]
    services__orchestrator -->|1| services__web
    services__orchestrator -->|1| services__projector
